# This rule is not used by the project podoperator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the workloads.sfcompute.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: podoperator
    app.kubernetes.io/managed-by: kustomize
  name: workload-editor-role
rules:
- apiGroups:
  - workloads.sfcompute.com
  resources:
  - workloads
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - workloads.sfcompute.com
  resources:
  - workloads/status
  verbs:
  - get
