# This rule is not used by the project podoperator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over workloads.sfcompute.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: podoperator
    app.kubernetes.io/managed-by: kustomize
  name: workload-admin-role
rules:
- apiGroups:
  - workloads.sfcompute.com
  resources:
  - workloads
  verbs:
  - '*'
- apiGroups:
  - workloads.sfcompute.com
  resources:
  - workloads/status
  verbs:
  - get
